### ISSUE TITLE
missing activation values for leaf node with a single incoming edge

### ISSUE THREAD

**Issue by csqsiew** [csqsiew/spreadr#1]
library(spreadr)
library(tidyverse)
g_d_mat <- matrix(c(
    0,    0,    0,    1,    0,#
    1,    0,    0,    1,    0,#
    0,    0,    0,    1,    0,#
    0,    1,    0,    0,    0,
    1,    1,    0,    0,    0), nrow = 5, ncol = 5) %>% t()
g_d_mat

spreadr(g_d_mat, data.frame(node = 1, activation = 20), retention = 0, time = 3, suppress = 0,
        decay = 0)

node activation time
1     1   0.000000    1
2     2  10.000000    1
3     3   0.000000    1
4     4   0.000000    1
5     5  10.000000    1
6     1   0.000000    2
7     2   0.000000    2
8     3   0.000000    2
9     4   5.000000    2
10    5   5.000000    2
11    1   1.666667    3
12    2   1.666667    3
**13    3   0.000000    3**
14    4   0.000000    3
15    5   0.000000    3

**Comment by ning-y** [comment]
The main change is from this:

https://github.com/csqsiew/spreadr/blob/59e9a50891d7a09bb07d3a02d0f840709a59bf88/src/create_mat_t.cpp#L12-L13

to this:

https://github.com/csqsiew/spreadr/blob/1bfe090f676bf2f74ed4f686b8f9863cffa89cf3/src/create_mat_t.cpp#L12-L13

In the first snippet, terminal nodes only retain a proportion of their activation, with the unretained activation going nowhere --- therefore appearing missing. The second snippet fixes this by first checking if a node is terminal or not. If it is terminal, then it should retain *all* (rather than just a proportion) of its activation.

The decay parameter still works as expected, because that step is implemented downstream of this change (in the R part).
